In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
class Environment:
    def __init__(self, rows, columns):
        self.map_rows = rows
        self.map_cols = columns
        
    def setGoalState(self, x, y):
        self.goal_state = (x, y)
        
    def setStart(self, x, y):
        self.start = (x, y)
        
    def setHoles(self, holes):
        self.holes = holes
        
    def getGoalState(self):
        return self.goal_state
    
    def getStart(self):
        return self.start
    
    def getHoles(self):
        return self.holes
        
    def getSize(self):
        return self.map_rows, self.map_cols

In [3]:
class State:
    def __init__(self, x, y):
        self.loc = (x, y)
        self.isEnd = False
        
    def getLoc(self):
        return self.loc
        
    def getReward(self):
        if self.loc == goal_state:
            return 10 
        elif self.loc in holes:
            return -5
        else:
            return -1
    
    def isEndFunc(self):
        if (self.loc == goal_state):
            self.isEnd = True    
    
    def nextLoc(self, action):        
        if action == "up":                
            nextState = (self.loc[0] - 1, self.loc[1])                
        elif action == "down":
            nextState = (self.loc[0] + 1, self.loc[1])
        elif action == "left":
            nextState = (self.loc[0], self.loc[1] - 1)
        else:
            nextState = (self.loc[0], self.loc[1] + 1)
           
        if (nextState[0] >= 0) and (nextState[0] <= map_rows-1):
            if (nextState[1] >= 0) and (nextState[1] <= map_cols-1):                    
                    return nextState
        return self.loc
    
    def conversion(self):
        return map_cols * self.loc[0] + self.loc[1]

In [9]:
class Agent:
    def __init__(self):
        self.actions = ["up", "down", "left", "right"]
        
        #EVIRONMENT
        self.env = Environment(map_rows, map_cols)
        self.env.setGoalState(goal_state[0], goal_state[1])
        self.env.setStart(start[0], start[1])
        self.env.setHoles(holes)
        
        #Q_TABLE
        self.state_size = map_rows * map_cols
        self.action_size = len(self.actions)
        self.qtable = np.zeros((self.state_size, self.action_size))
        
        self.rewards = []
                   
    def printTable(self):
        print("------------------- Q LEARNING TABLE ------------------")
        print(self.qtable)
        print("-------------------------------------------------------")
        
    def printPath(self):
        rows, cols = self.env.getSize()
        
        start = self.env.getStart()
        state = State(start[0], start[1])      
        while True:
            print(state.getLoc())
            location = state.getLoc()
            if state.getLoc()[0]==self.env.getGoalState()[0] and state.getLoc()[1]==self.env.getGoalState()[1]:
                break
            old_state = state.conversion()
            action = np.argmax(self.qtable[old_state, :])                           
            nextstate = state.nextLoc(self.actions[action])                   
            state = State(nextstate[0],nextstate[1])                                
        
                 
    def q_learning(self):
        start = self.env.getStart()
        
        for episode in range(total_episodes):
            state = State(start[0],start[1])
            total_rewards = 0
            for step in range(max_steps):
                exp_exp_tradeoff = random.uniform(0, 1)
                old_state  = state.conversion()
        
                epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
        
                if exp_exp_tradeoff > epsilon:
                    action = np.argmax(self.qtable[old_state, :])
                else:
                    action = random.randint(0, len(self.actions)-1)
                           
                nextState = state.nextLoc(self.actions[action])
                new_state  = State(nextState[0], nextState[1]).conversion()
                reward = state.getReward()
                total_rewards += reward
                
                self.qtable[old_state, action] = (1 - learning_rate) * self.qtable[old_state, action] + learning_rate * (reward + gamma * np.max(self.qtable[new_state, :]))
                
                state = State(nextState[0],nextState[1])
                
            self.rewards.append(total_rewards)

In [10]:
total_episodes = 10000
learning_rate = 0.5
max_steps = 99
gamma = 0.95
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [11]:
map_rows = 5
map_cols = 5
goal_state = (4, 4)
start = (0, 0)
holes = [(0,2), (1,1), (2,3), (3,0), (4,3)]

In [12]:
ag = Agent()
ag.q_learning()
ag.printTable()

------------------- Q LEARNING TABLE ------------------
[[118.65487014 125.95249488 118.65487014 122.34249488]
 [122.34084073 129.83420514 118.64883458 129.82329207]
 [123.47691437 136.92457548 117.70826229 137.72000354]
 [141.67894245 150.22597911 129.7576014  150.23180528]
 [150.22989997 159.191375   141.71993542 150.23161416]
 [118.65487014 133.63420514 125.95249488 129.83420514]
 [118.34248157 137.72021594 121.95249151 137.72021417]
 [129.72781694 150.23180625 129.8207722  150.21885354]
 [141.71925398 155.39078603 141.68476474 159.191375  ]
 [150.23180608 168.6225     150.23180389 159.19137426]
 [125.95249488 137.92021594 133.63420514 141.72021594]
 [129.83420514 150.23180625 133.63420514 150.23180625]
 [141.72021587 159.191375   141.72021589 155.39137346]
 [146.2318061  164.6225     146.23180625 164.62249999]
 [159.191375   178.55       155.391375   168.6225    ]
 [129.63419303 142.97376732 133.92018289 146.23180625]
 [141.72021594 155.761875   137.92021594 159.191375  ]
 [150.231

In [13]:
ag.printPath()

(0, 0)
(1, 0)
(2, 0)
(2, 1)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(4, 4)
